version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: logging_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: asi_logging
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - logging_network

  backend:
    build: ./backend
    container_name: logging_backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: asi_logging
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - logging_network
      - asi_shared_network

  frontend:
    build: ./frontend
    container_name: logging_frontend
    restart: unless-stopped
    environment:
      VITE_API_TARGET: http://backend:5000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - logging_network

volumes:
  pgdata:


networks:
  logging_network:
    driver: bridge
  asi_shared_network:
    external: true
